application: metatictactoe
version: 4
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- channel_presence

handlers:
- url: /test.*
  script: gaeunit.py

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /.*
  script: Main.py
